---
# tasks file for auth
- name: load vars from ansible vault
  include_vars:
    file: "./vars/secrets.yml"

- name: configure OIDC auth
  ansible.builtin.import_tasks: configure_oidc_auth.yml
  when: idp.type | default("OpenID")

#- name: configure HTPasswd auth
#  ansible.builtin.import_tasks: configure_htpasswd_auth.yml
#  when: idp.type | default("HTPasswd")